### ISSUE TITLE
Misleading error message when missing GCS application-default credentials

### ISSUE THREAD

**Issue by honnibal** [justindujardin/pathy#43]
We have a few `assert self.client is not None, _MISSING_DEPS` in the `pathy.gcs` module. This displays an error message about installing the google cloud libraries.

However, the missing installation is not the only reason we can end up with `self.client is None`. We can also end up in that state when the libraries are installed, but the credentials can't be found. This is especially problematic since the GCS authentication is kind of confusing. I still don't really understand the application-default credentials thing.

Anyway, I got this error:

```
You are using the GCS functionality of Pathy without
having the required dependencies installed.

Please try installing them:

    pip install pathy[gcs]
```

But the actual solution was:

```
gcloud auth login
gcloud auth application-default login
```

**Comment by justindujardin** [comment]
Nice catch! I looked at this a bit, and I think we have two options:

- Stop handling `DefaultCredentialsError` in the GCS client and let it bubble up. This way you'll see the underlying auth error which includes a link to a google site about installing the Cloud SDK. This is what smart_open does when you use streaming methods.
- Handle `DefaultCredentialsError` and provide a custom error like for missing deps. We'll probably also want to handle it for smart_open streams to ensure consistent behavior.

I don't have a strong preference, because the GCS error contains a helpful link, so we'll end up with a useful error either way.

**Comment by honnibal** [comment]
For now let's at least "do no harm", and get out of the way of the underlying error? If we think we've got a better message later we can add it.
